# Generated by Django 2.1.1 on 2018-09-19 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('categories', models.TextField(max_length=1500)),
                ('grade', models.CharField(max_length=5)),
                ('nutriments', models.TextField(max_length=1500)),
                ('code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('gender', models.SmallIntegerField(choices=[(0, 'Girl'), (1, 'Boy'), (2, 'Other')], db_index=True, default='2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.Product'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.User'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='substitute',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='store.Product'),
        ),
    ]
